name: cinemix_ui
description: "An online movie ticket booking application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  accordion: ^2.6.0
  barcode: ^2.2.7
  bloc: ^8.1.3
  carousel_slider: ^4.2.1
  country_icons: ^3.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_pw_validator: ^1.6.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  http: ^1.2.1
  iconsax_plus: ^1.0.0
  input_quantity: ^2.3.2
  intl: ^0.19.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  pinput: ^4.0.0
  provider: ^6.1.2
  readmore: ^3.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  social_auth_btn_kit: ^0.1.3
  solar_icons: ^0.0.5
  swipe_to: ^1.0.6

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/actors/
    - assets/images/directors/
    - assets/images/movies/
    - assets/images/payments/
    - assets/images/splash/
    - assets/lottie/

flutter_native_splash:
  color: "#000000"
  android_12:
    image: assets/images/splash/android12splash.png
  ios: false
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21
