name: cinemix_ui
description: "An online movie ticket booking application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6

  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  http: ^1.2.1
  iconify_flutter: 0.0.5
  intl: ^0.19.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  solar_icons: ^0.0.5
  date_field: ^4.0.0
  date_picker_textfield: ^1.0.4
  intl_phone_field: ^3.1.0
  board_datetime_picker: ^1.6.1
  swipe_to: ^1.0.6

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
